name: Create Release

on:
    workflow_dispatch
    # push:
    #     branches:
    #         - main

jobs:
    get_use_outputs:
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.read_version.outputs.version }}
            mcworld_files: ${{ steps.find_files.outputs.mcworld_files }}
            mcaddon_files: ${{ steps.find_files.outputs.mcaddon_files }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name:
              id: read_version
              run: |
                  version=$(cat VERSION.md)
                  echo "version=$version" >> "$GITHUB_OUTPUT"

            - name: Find mcworld and mcaddon files
              id: find_files
              run: |
                  mcworld_files=$(find . -name "informant_*.*.*.mcworld" -print0 | tr '\0' '\n' | sed 's/^.\//' | paste -sd ',' -)
                  mcaddon_files=$(find . -name "informant_addon_*-*-*.mcaddon" -print0 | tr '\0' '\n' | sed 's/^.\//' | paste -sd ',' -)
                  echo "mcworld_files=$mcworld_files" >> "$GITHUB_OUTPUT"
                  echo "mcaddon_files=$mcaddon_files" >> "$GITHUB_OUTPUT"

    release:
        needs: get_use_outputs
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.set_output.outputs.upload_url }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ env.version}}
                  release_name: ${{ env.version}}
                  body_path: ./RELEASE.md
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  version: ${{ needs.get_use_outputs.outputs.version }}
            - name: Set output
              id: set_output
              run: echo "upload_url=${{ steps.create_release.outputs.upload_url }}" >> "$GITHUB_OUTPUT"

    assets:
        needs: [release, get_use_outputs]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Upload mcworld files
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ env.upload_url}}
                  asset_path: ./${{ env.mcworld_files }}
                  asset_name: ${{ env.mcworld_files }}
                  asset_content_type: application/zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  mcworld_files: ${{ needs.get_use_outputs.outputs.mcworld_files }}
                  upload_url: ${{ needs.release.outputs.upload_url }}

            - name: Upload mcaddon files
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ env.upload_url}}
                  asset_path: ./${{ env.mcaddon_files }}
                  asset_name: ${{ env.mcaddon_files }}
                  asset_content_type: application/zip
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  mcaddon_files: ${{ needs.get_use_outputs.outputs.mcaddon_files }}
                  upload_url: ${{ needs.release.outputs.upload_url }}
